USE Workshop;
DROP TABLE IF EXISTS `Employee`;
CREATE TABLE IF NOT EXISTS `Employee` (
    `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `Employee_Name` CHAR(40) NOT NULL DEFAULT '',
    `EmpID` BIGINT(20) NOT NULL,
    `MarriedID` INT(5) NOT NULL, 
    `MaritalStatusID` INT(5) NOT NULL,
    `GenderID` INT(5) NOT NULL,
    `EmpStatusID` INT(5) NOT NULL,
    `DeptID` INT(5) NOT NULL,
    `PerfScoreID` INT(5) NOT NULL,
    `FromDiversityJobFairID` INT(5) NOT NULL,
    `Salary` INT(10) NOT NULL,
    `Termd` INT(5) NOT NULL,
    `PositionID` INT(10) NOT NULL,
    `Position` CHAR(40) NOT NULL,
    `State` CHAR(10) NOT NULL,
    `Zip` INT(5) NOT NULL,
    `DOB` DATE NOT NULL,
    `Sex` CHAR(2) NOT NULL,
    `MaritalDesc` CHAR(10) NOT NULL,
    `CitizenDesc` CHAR(20) NOT NULL,
    `HispanicLatino` CHAR(3) NOT NULL,
    `RaceDesc` CHAR(32) NOT NULL,
    `DateofHire` DATE NOT NULL,
    `DateofTermination` DATE,
    `TermReason` CHAR(32) NOT NULL,
    `EmploymentStatus` CHAR(22) NOT NULL,
    `Department` CHAR(20) NOT NULL,
    `ManagerName` CHAR(18) NOT NULL,
    `ManagerID` INT(10),
    `RecruitmentSource` CHAR(23) NOT NULL,
    `PerformanceScore` CHAR(17) NOT NULL,
    `EngagementSurvey` FLOAT(4,2) NOT NULL,
    `EmpSatisfaction` INT(10) NOT NULL,
    `SpecialProjectsCount` INT(10)  NOT NULL,
    `LastPerformanceReview_Date` DATE  NOT NULL, 
    `DaysLateLast30` INT(19)  NOT NULL,
    `Absences` INT(10) NOT NULL,
    PRIMARY KEY (`ID`) /*T![clustered_index] CLUSTERED */,
    KEY `Employee_Name` (`Employee_Name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=40510553;

