[lightning]
# Log
level = "info"
file = "tidb-lightning-workshop.log"
table-concurrency = 1
index-concurrency = 1
region-concurrency = 1
io-concurrency = 1
max-error = 0
task-info-schema-name = "lightning_task_info"
meta-schema-name = "lightning_metadata"

[tikv-importer]
backend = "tidb"
incremental-import = false
sorted-kv-dir = "../stage/sorted-kv-dir-1"

[mydumper]
data-source-dir = "./misc/"
filter = ['*.*', '!mysql.*', '!sys.*', '!INFORMATION_SCHEMA.*', '!PERFORMANCE_SCHEMA.*', '!METRICS_SCHEMA.*', '!INSPECTION_SCHEMA.*']
strict-format = true

[mydumper.csv]
separator = ','
delimiter = '"'
terminator = ''
header = true
not-null = false
null = '\N'
backslash-escape = true
trim-last-separator = false

[tidb]
host = "127.0.0.1"
port = 4000
user = "imp"
password = "q1w2e3R4_"
status-port = 10080
pd-addr = "127.0.0.1:2379"